version: "3.8"

services:
  login-service:
    build:
      context: ./login-service
    ports:
      - "5001:80"
    container_name: login-service
    networks:
      - ecommerce-net

  product-service:
    build:
      context: ./product-service
    ports:
      - "5002:3000"
    container_name: product-service
    networks:
      - ecommerce-net

  order-service:
    build:
      context: ./order-service
    ports:
      - "5003:80"
    container_name: order-service
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
